# Generated by Django 3.2.7 on 2021-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('to', models.TextField()),
                ('reciver', models.TextField()),
                ('subject', models.TextField()),
                ('NotableItem', models.TextField()),
                ('FutureActions', models.TextField()),
                ('signe', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('file_name', models.TextField()),
                ('confirm', models.BooleanField()),
            ],
        ),
    ]
