# Generated by Django 3.2.7 on 2022-05-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signe', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('reciver', models.TextField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('NotableItem', models.TextField()),
                ('FutureActions', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('file_name', models.TextField()),
                ('confirm', models.BooleanField()),
                ('singe_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.signe')),
            ],
        ),
    ]
