# Generated by Django 3.2.7 on 2022-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.CharField(max_length=500)),
                ('signe', models.TextField(null=True)),
                ('functions', models.TextField()),
                ('types', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
