# Generated by Django 3.2.7 on 2022-05-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signe', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.CharField(max_length=500)),
                ('functions', models.TextField()),
                ('types', models.TextField()),
                ('comment', models.TextField()),
                ('singe_chek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChekList.signe')),
            ],
        ),
    ]
