# Generated by Django 3.2.7 on 2021-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=500)),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('date2', models.TextField()),
                ('category', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('kind', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('file_name', models.TextField()),
                ('confirm', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('signe', models.TextField(null=True)),
            ],
        ),
    ]
