# Generated by Django 3.2.7 on 2021-11-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0006_alter_parameter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('date2', models.TextField()),
                ('category', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('kind', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('file_name', models.TextField()),
                ('globall', models.BooleanField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='archive',
            name='name',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
