# Generated by Django 3.2.7 on 2021-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0007_auto_20211111_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.TextField(),
        ),
    ]
