# Generated by Django 3.2.7 on 2021-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0009_rename_globall_checklist_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='date',
            field=models.TextField(),
        ),
    ]
