# Generated by Django 3.2.7 on 2021-11-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChekList', '0010_alter_checklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='time',
            field=models.TextField(),
        ),
    ]
